First pass at making this work on vanilla dokku

diff --git a/commands b/commands
--- a/commands
+++ b/commands
@@ -1,7 +1,12 @@
 #!/usr/bin/env bash
 
-source "$(dirname $0)/../dokku_common"
+source "$(dirname $0)/../common/functions"
 source "$(dirname $0)/vars"
+
+function verify_max_args() {
+	local MAX_ARGS="$1"
+	[[ $# -le $((MAX_ARGS+1)) ]] || fail "Invalid number of arguments ($(($#-1)), expected $MAX_ARGS)."
+}
 
 case "$1" in
 	nginx:cache:enable)
